a = float(input('Введите число а: '))
b = float(input('Введите число b: '))
c = float(input('Введите число c: '))
print('x1 =', (-b + (b**2 - 4*a*c)**0.5)/(2*a))
print('x2 =', (-b - (b**2 - 4*a*c)**0.5)/(2*a))
